# Generated by Django 3.0.7 on 2020-06-19 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20200619_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='post',
        ),
    ]
