# Generated by Django 3.0.7 on 2020-06-19 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_city_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='post',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='main_app.Post'),
        ),
    ]
