# Generated by Django 3.0.7 on 2020-06-19 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20200619_2206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
