<<<<<<< HEAD
# Generated by Django 3.0.7 on 2020-06-22 18:10
=======
# Generated by Django 3.0.7 on 2020-06-22 18:27
>>>>>>> submaster

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_auto_20200622_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.City'),
        ),
    ]
